# Generated by Django 3.0.6 on 2020-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymadmin', '0002_student_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
