# Generated by Django 3.0.6 on 2020-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.IntegerField(default=0),
        ),
    ]
