# Generated by Django 3.0.6 on 2020-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_user_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
